### ISSUE TITLE
captcha_trainer的compact分支训练结果该如何调用

### ISSUE THREAD

**Issue by radiation-chan** [kerlomz/captcha_library_c#3]
captcha_trainer的compact分支训练结果该如何调用?
通过python3调用从release中下载的CaptchaLibrary.dll会报错

**Comment by radiation-chan** [comment]
同目录下有tensorflow.dll
原来的tensorflow.dll会报错
`ERROR: Creating graph in session failed...Not found: Op type not registered 'LeakyRelu' in binary running on RADIATION-CHAN. Make sure the Op and Kernel are registered in the binary running in this process.
ERROR: RUN failed...
Invalid argument: Session was not created with a graph before Run()!
Traceback (most recent call last):
  File "E:/captcha_project/result_test/test.py", line 14, in <module>
    print("PredictFile:", string_at(result_file).decode())
  File "D:\Miniconda3\lib\ctypes\__init__.py", line 497, in string_at
ERROR: RUN failed...
Invalid argument: Session was not created with a graph before Run()!
    return _string_at(ptr, size)
OSError: exception: access violation reading 0x0000000000000000`
